name: notification_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.8
  onesignal_flutter: ^5.3.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
